<?php
/**
 * Montana theme setup.
 *
 * Montana is a block theme: the layout lives in templates/*.html, the design
 * system in theme.json (generated by .dev/build_theme.py), and the sections in
 * patterns/*.php (generated by .dev/build_patterns.py). This file carries only
 * what those cannot express — supports flags, asset enqueues, block styles,
 * pattern categories, and the modules in inc/.
 *
 * @package Montana
 */

defined( 'ABSPATH' ) || exit;

define( 'MONTANA_VERSION', '1.0.2' );

/**
 * Theme supports.
 */
function montana_setup() {
	load_theme_textdomain( 'montana', get_template_directory() . '/languages' );

	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'automatic-feed-links' );
	add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script' ) );
	add_theme_support( 'editor-styles' );
	add_theme_support( 'responsive-embeds' );
	add_theme_support( 'align-wide' );
	add_theme_support( 'wp-block-styles' );
	add_theme_support(
		'custom-logo',
		array(
			'height'      => 92,
			'width'       => 112,
			'flex-height' => true,
			'flex-width'  => true,
		)
	);

	// style.css is loaded into the editor canvas too, so the components below
	// look the same there as on the front end.
	add_editor_style( 'style.css' );
}
add_action( 'after_setup_theme', 'montana_setup' );

/**
 * Front-end styles.
 */
function montana_enqueue_styles() {
	// The theme's own stylesheet by its template path, not get_stylesheet_uri():
	// under a child theme that returns the CHILD's style.css, and every
	// component style in this file would silently stop loading. A child theme
	// enqueues its own stylesheet, as with Twenty Twenty-Five.
	wp_enqueue_style( 'montana-style', get_template_directory_uri() . '/style.css', array(), MONTANA_VERSION );
}
add_action( 'wp_enqueue_scripts', 'montana_enqueue_styles' );

/**
 * Block style variations.
 *
 * Registered here rather than in theme.json because a style variation needs a
 * label for the editor's Styles panel. The CSS behind each one lives in
 * style.css, which always loads: a `style_handle` only enqueues while WordPress
 * serves separate block assets, and any plugin can switch that off site-wide.
 * .dev/dead-selectors.py fails the build if one of these has no CSS.
 */
function montana_register_block_styles() {
	$styles = array(
		'core/paragraph'    => array(
			array( 'montana-eyebrow', __( 'Eyebrow', 'montana' ) ),
		),
		'core/group'        => array(
			array( 'montana-box', __( 'Pale panel', 'montana' ) ),
		),
		'core/button'       => array(
			array( 'montana-outline', __( 'Outline', 'montana' ) ),
			array( 'montana-pill', __( 'Pill', 'montana' ) ),
		),
		'core/list'         => array(
			array( 'montana-dots', __( 'Dots', 'montana' ) ),
		),
		'core/social-links' => array(
			array( 'montana-plain', __( 'Plain icons', 'montana' ) ),
		),
	);

	foreach ( $styles as $block => $variations ) {
		foreach ( $variations as $variation ) {
			list( $name, $label ) = $variation;
			register_block_style(
				$block,
				array(
					'name'  => $name,
					'label' => $label,
				)
			);
		}
	}
}
add_action( 'init', 'montana_register_block_styles' );

/**
 * Scroll reveals, the photograph sliders, the video popup, the header that
 * turns black once the page scrolls, and the booking form's date pair.
 *
 * Deferred and in the footer: everything the script does is an enhancement, so
 * it never needs to hold up rendering. `montana_enable_scroll_animations`
 * switches off the reveals and the sliders' autoplay, and leaves the arrows
 * and the video popup, which are behaviour rather than decoration.
 *
 * The settings go in as JSON, not through wp_localize_script(), which turns
 * `false` into an empty string that the script would read as "on".
 */
function montana_enqueue_interactions() {
	wp_enqueue_script(
		'montana-interactions',
		get_template_directory_uri() . '/assets/js/interactions.js',
		array(),
		MONTANA_VERSION,
		array(
			'in_footer' => true,
			'strategy'  => 'defer',
		)
	);

	wp_add_inline_script(
		'montana-interactions',
		'window.montanaMotion = ' . wp_json_encode(
			array(
				'enabled'     => (bool) apply_filters( 'montana_enable_scroll_animations', true ),
				'videoLabel'  => __( 'Video', 'montana' ),
				'closeLabel'  => __( 'Close video', 'montana' ),
				'sliderLabel' => __( 'Photographs', 'montana' ),
				'prevLabel'   => __( 'Previous photograph', 'montana' ),
				'nextLabel'   => __( 'Next photograph', 'montana' ),
			)
		) . ';',
		'before'
	);
}
add_action( 'wp_enqueue_scripts', 'montana_enqueue_interactions' );

/**
 * Pattern categories.
 */
function montana_register_pattern_categories() {
	$categories = array(
		'montana-sections' => array(
			'label'       => __( 'Montana: sections', 'montana' ),
			'description' => __( 'Full-width sections for building pages.', 'montana' ),
		),
		'montana-pages'    => array(
			'label'       => __( 'Montana: pages', 'montana' ),
			'description' => __( 'Complete page layouts.', 'montana' ),
		),
	);

	foreach ( $categories as $slug => $args ) {
		register_block_pattern_category( $slug, $args );
	}
}
add_action( 'init', 'montana_register_pattern_categories' );

/**
 * Expand shortcodes in a Shortcode block rendered by a template.
 *
 * core/shortcode's render callback only runs wpautop(); the expansion comes from
 * do_shortcode on `the_content`, which does not run for a block template or a
 * template part. The footer's newsletter form lives in a template part, so
 * without this the footer would print `[montana_form …]` as text. Running
 * do_shortcode on already-expanded output is a no-op, so this is safe on
 * post content too.
 *
 * @param string $content Rendered block.
 * @return string
 */
function montana_render_shortcode_block( $content ) {
	return do_shortcode( $content );
}
add_filter( 'render_block_core/shortcode', 'montana_render_shortcode_block' );

require get_template_directory() . '/inc/front-page-setup.php';
require get_template_directory() . '/inc/booking.php';
require get_template_directory() . '/inc/forms.php';
require get_template_directory() . '/inc/woocommerce.php';
require get_template_directory() . '/inc/scheme.php';
require get_template_directory() . '/inc/updates.php';
